# Base image
FROM python:3.9-slim-buster

# Version C library to use
ARG GLIBC_VERSION='2.37'

# Install build dependencies
RUN apt-get update && \
    apt-get install -y build-essential wget && \
    rm -rf /var/lib/apt/lists/*

# Download and extract glibc source code and install glibc
WORKDIR /usr/src
RUN wget http://ftp.gnu.org/gnu/libc/glibc-${GLIBC_VERSION}.tar.xz && \
    tar -xf glibc-${GLIBC_VERSION}.tar.xz && \
    rm glibc-${GLIBC_VERSION}.tar.xz
    cd ./glibc-${GLIBC_VERSION} && \
    mkdir build && \
    cd build && \
    ../configure --prefix=/usr/local/glibc && \
    make -j$(nproc) && \
    make install

# Set environment variables for C library
ENV LD_LIBRARY_PATH=/usr/local/glibc/lib

# Copy Python app files to container
WORKDIR /usr/src/app
COPY requirements.txt .
COPY flask_https_server.py .
COPY server.crt .
COPY server.key .

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Expose port 5000 for the Flask app
EXPOSE 5000

# Start the app
CMD ["python3", "flask_https_server.py"]